fullnameOverride: "bonusblock-user-dashboard-staging"
replicaCount: 1
logFormat: nginx_ssl_reqid_upstream_time

ingress:
  enabled: true
  hosts:
    - host: ui3.staging.alter.network
      paths:
        - path: /
# Uncomment 3 lines before for maintenance mode
#          backend:
#            service:
#              name: bonusblock-user-dashboard-maintenance
  tls:
    - hosts:
        - ui3.staging.alter.network
      secretName: bonusblock-user-dashboard-staging-ssl
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: office.altermail.lv
    external-dns.alpha.kubernetes.io/ttl: "300"
    traefik.ingress.kubernetes.io/router.middlewares: default-add-reqid@kubernetescrd
